/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AMC1.Comun;

import AMC1.DyV.AlgoritmosDyV;
import AMC1.DyV.Desviacion;
import AMC1.DyV.HeapSort;
import AMC1.Voraces.AlgoritmosV;
import AMC1.Voraces.Arista;
import AMC1.Voraces.Grafo;
import java.awt.BorderLayout;
import java.awt.Color;
import java.math.RoundingMode;
import java.nio.file.Paths;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.filechooser.FileFilter;


public class Menu extends javax.swing.JFrame {

    ArrayList<Vertice> vertices;
    ArrayList<Arista> aristas;
    Grafo g;
    JDialog dialogoAyuda;
    private SwingWorker<Void, Void> verGrafo;
    JOptionPane paneCargando;
    Clip musica;
    boolean mejoraDyV; //Activar mejora del DyV dividiendo por eje X/Y
    //Grafica graficaCentral;

    public Menu() {
        initComponents();
        vertices = new ArrayList<>();
        //cargarVector();
        anadirFilaTabla();
        this.getContentPane().setBackground(Color.DARK_GRAY);
        this.setLocationRelativeTo(null);
        graficaGrafo.addPuntos(vertices);
        graficaCentral.addPuntos(vertices);
        graficaDatos.addPuntos(vertices);
        graficaDatos.representa();
        graficaCentral.representa();
        graficaGrafo.representa();
        mejoraDyV=true;

    }
    public void verGrafo()
    {
        new SwingWorker<Void, Void>(){
        @Override
        protected Void doInBackground() throws Exception {
            
            graficaGrafo.addPuntos(vertices);
            graficaGrafo.addAristas(g.cjtoAristas);
            graficaGrafo.representa();
            
            
            return null;
        }

        @Override
        protected void done() {
            //dialogoAyuda.setVisible(false);
            musica.stop();
            paneCargando.setVisible(false);
              
            
            
        }
    }.execute();
        
    }
    public void anadirFilaTabla() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[3];

        if (!jTable1.getSelectionModel().isSelectionEmpty()) {
            for (int i = 0; i < vertices.size(); i++) {
                rowData[0] = vertices.get(i).getX();
                rowData[1] = vertices.get(i).getY();
                model.addRow(rowData);
            }
        } else {
            model.setRowCount(0);

            for (int i = 0; i < vertices.size(); i++) {
                rowData[0] = vertices.get(i).getID();
                rowData[1] = vertices.get(i).getX();
                rowData[2] = vertices.get(i).getY();
                model.addRow(rowData);
            }
        }
    }

    public void anadirFilaAristas(ArrayList<Arista> aristas)
    {
        DefaultTableModel model = (DefaultTableModel) aristasTable.getModel();
        Object rowData[] = new Object[3];
        model.setRowCount(0);
        
        
            aristas.forEach((Arista a)-> {
                rowData[0] = a.getOrigen().getID();
                rowData[1] = a.getDestino().getID();
                rowData[2] = a.getCoste();
                
                model.addRow(rowData);
            });
    }
    
    public void actualizarDatos()
    {
        graficaDatos.removeAll();
        anadirFilaTabla();
        graficaDatos.addPuntos(vertices);
        graficaDatos.representa();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JTabbedPane();
        Datos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        puntoX = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        puntoY = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        eliminarPane = new javax.swing.JTextPane();
        eliminarBut = new javax.swing.JButton();
        cargarBut = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        examinarBut = new javax.swing.JButton();
        guardarBut = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        mostrarPuntosBut = new javax.swing.JButton();
        aleatoriosBut = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        aleatoriosPane = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        rangoIzqPane = new javax.swing.JTextPane();
        rangoIzqPane.setText("0");
        jScrollPane11 = new javax.swing.JScrollPane();
        rangoDchPane = new javax.swing.JTextPane();
        rangoDchPane.setText("100");
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        graficaDatos = new AMC1.Comun.Grafica();
        jLabel12 = new javax.swing.JLabel();
        cargarFichBut = new javax.swing.JButton();
        guardarFichBut = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        modoEtiquetaDatos = new javax.swing.JComboBox<>();
        ficheroCombo = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        eP4 = new javax.swing.JLabel();
        dPunto2 = new javax.swing.JLabel();
        dP5 = new javax.swing.JLabel();
        dPunto1 = new javax.swing.JLabel();
        eP1 = new javax.swing.JLabel();
        dPerimetro = new javax.swing.JLabel();
        dP2 = new javax.swing.JLabel();
        dP1 = new javax.swing.JLabel();
        ePerimetro = new javax.swing.JLabel();
        eP2 = new javax.swing.JLabel();
        ePunto1 = new javax.swing.JLabel();
        eP3 = new javax.swing.JLabel();
        eTiempo = new javax.swing.JLabel();
        ePunto2 = new javax.swing.JLabel();
        ePunto3 = new javax.swing.JLabel();
        exhaustivo = new javax.swing.JButton();
        divideyvenceras = new javax.swing.JButton();
        eP5 = new javax.swing.JLabel();
        dP4 = new javax.swing.JLabel();
        dTiempo = new javax.swing.JLabel();
        dP3 = new javax.swing.JLabel();
        dPunto3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        graficaCentral = new AMC1.Comun.Grafica();
        modoEtiquetaDyV = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        ayudaCheck = new javax.swing.JCheckBox();
        dividirXCheck = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        primBut = new javax.swing.JButton();
        kruskalBut = new javax.swing.JButton();
        guardarGrafosBut = new javax.swing.JButton();
        graficaGrafo = new AMC1.Comun.Grafica();
        jScrollPane1 = new javax.swing.JScrollPane();
        aristasTable = new javax.swing.JTable();
        costeLabel = new javax.swing.JLabel();
        tiempoLabel = new javax.swing.JLabel();
        verGrafoBut = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        modoEtiquetaGrafo = new javax.swing.JComboBox<>();
        desarrolloCheck = new javax.swing.JCheckBox();
        greedyBut = new javax.swing.JButton();
        datosBut = new javax.swing.JButton();
        dyvBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estrategias Algorítmicas - Victor M. Rodríguez y Fran J. Beltrán");

        Panel.setBackground(new java.awt.Color(204, 204, 204));
        Panel.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        Panel.setAlignmentX(0.0F);
        Panel.setEnabled(false);
        Panel.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        Panel.setMinimumSize(new java.awt.Dimension(142, 104));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Punto", "X", "Y"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel7.setText("Añadir Puntos");

        puntoX.setAutoscrolls(false);
        jScrollPane2.setViewportView(puntoX);

        puntoY.setAutoscrolls(false);
        jScrollPane5.setViewportView(puntoY);

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel2.setText("X: ");

        jLabel3.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel3.setText("Y: ");

        jButton3.setFont(new java.awt.Font("SF Pro Display", 1, 12)); // NOI18N
        jButton3.setText("Insertar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel8.setText("Eliminar Puntos");

        jLabel6.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel6.setText("ID");

        eliminarPane.setAutoscrolls(false);
        jScrollPane6.setViewportView(eliminarPane);

        eliminarBut.setFont(new java.awt.Font("SF Pro Display", 1, 12)); // NOI18N
        eliminarBut.setText("Eliminar");
        eliminarBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButActionPerformed(evt);
            }
        });

        cargarBut.setFont(new java.awt.Font("SF Pro Display", 1, 12)); // NOI18N
        cargarBut.setText("Eliminar TODOS");
        cargarBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarButActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel13.setText("Ficheros");

        jLabel4.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel4.setText("Cargar Puntos");

        examinarBut.setFont(new java.awt.Font("SF Pro Display", 1, 12)); // NOI18N
        examinarBut.setText("Examinar");
        examinarBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examinarButActionPerformed(evt);
            }
        });

        guardarBut.setFont(new java.awt.Font("SF Pro Display", 1, 12)); // NOI18N
        guardarBut.setText("Guardar");
        guardarBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel5.setText("Guardar Puntos");

        jLabel15.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel15.setText("Mostrar Puntos");

        mostrarPuntosBut.setFont(new java.awt.Font("SF Pro Display", 1, 12)); // NOI18N
        mostrarPuntosBut.setText("Mostrar");
        mostrarPuntosBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarPuntosButActionPerformed(evt);
            }
        });

        aleatoriosBut.setFont(new java.awt.Font("SF Pro Display", 1, 12)); // NOI18N
        aleatoriosBut.setText("Generar");
        aleatoriosBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aleatoriosButActionPerformed(evt);
            }
        });

        jScrollPane9.setViewportView(aleatoriosPane);

        jScrollPane10.setViewportView(rangoIzqPane);

        rangoDchPane.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane11.setViewportView(rangoDchPane);

        jLabel11.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel11.setText("Rango");

        jLabel10.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel10.setText("Cantidad");

        jLabel9.setFont(new java.awt.Font("SF Pro Display", 0, 12)); // NOI18N
        jLabel9.setText("Generar Aleatorios");

        javax.swing.GroupLayout graficaDatosLayout = new javax.swing.GroupLayout(graficaDatos);
        graficaDatos.setLayout(graficaDatosLayout);
        graficaDatosLayout.setHorizontalGroup(
            graficaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1027, Short.MAX_VALUE)
        );
        graficaDatosLayout.setVerticalGroup(
            graficaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel12.setText("Fichero TSP");

        cargarFichBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cargarFichBut.setText("Cargar");
        cargarFichBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarFichButActionPerformed(evt);
            }
        });

        guardarFichBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        guardarFichBut.setText("Guardar");
        guardarFichBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarFichButActionPerformed(evt);
            }
        });

        jLabel17.setText("Modo de Etiquetas");

        modoEtiquetaDatos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vi (X, Y)", "Vi", "vacío" }));
        modoEtiquetaDatos.setSelectedIndex(2);
        modoEtiquetaDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoEtiquetaDatosActionPerformed(evt);
            }
        });

        ficheroCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "CASO_MEJOR", "CASO_PEOR", "berlin52", "ch130", "ch150", "d493", "d657" }));
        ficheroCombo.setAutoscrolls(true);
        ficheroCombo.setName(""); // NOI18N
        ficheroCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficheroComboActionPerformed(evt);
            }
        });

        jLabel19.setText("Elegir del DataSet");

        javax.swing.GroupLayout DatosLayout = new javax.swing.GroupLayout(Datos);
        Datos.setLayout(DatosLayout);
        DatosLayout.setHorizontalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DatosLayout.createSequentialGroup()
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(DatosLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(modoEtiquetaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(DatosLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel3)))
                                .addGap(10, 10, 10)
                                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(77, 77, 77)
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(DatosLayout.createSequentialGroup()
                                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DatosLayout.createSequentialGroup()
                                        .addGap(180, 180, 180)
                                        .addComponent(jLabel9))
                                    .addGroup(DatosLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(DatosLayout.createSequentialGroup()
                                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(eliminarBut))
                                            .addComponent(cargarBut, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosLayout.createSequentialGroup()
                                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(12, 12, 12)
                                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(DatosLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(aleatoriosBut)))))
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DatosLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(guardarFichBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cargarFichBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(DatosLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(ficheroCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DatosLayout.createSequentialGroup()
                        .addComponent(graficaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1076, 1076, 1076)
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DatosLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mostrarPuntosBut))
                            .addGroup(DatosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addGroup(DatosLayout.createSequentialGroup()
                                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(guardarBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(examinarBut))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DatosLayout.setVerticalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosLayout.createSequentialGroup()
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DatosLayout.createSequentialGroup()
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DatosLayout.createSequentialGroup()
                                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(DatosLayout.createSequentialGroup()
                                            .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(eliminarBut))
                                            .addGap(34, 34, 34))
                                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cargarBut)))
                                    .addComponent(modoEtiquetaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(DatosLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(DatosLayout.createSequentialGroup()
                                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton3)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(DatosLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(DatosLayout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(aleatoriosBut)))
                                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(DatosLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane10)
                                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(3, 3, 3))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel12))
                                    .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(DatosLayout.createSequentialGroup()
                                            .addGap(38, 38, 38)
                                            .addComponent(guardarFichBut))
                                        .addGroup(DatosLayout.createSequentialGroup()
                                            .addGap(11, 11, 11)
                                            .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(cargarFichBut)
                                                .addComponent(ficheroCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(2, 2, 2))))
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DatosLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(15, 15, 15)
                                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(examinarBut))
                                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(guardarBut)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(mostrarPuntosBut))
                                .addGap(396, 396, 396))
                            .addComponent(graficaDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(DatosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(142, 142, 142))
        );

        Panel.addTab("Datos", Datos);

        eP4.setText("-");

        dPunto2.setText("Punto 2:");

        dP5.setText("-");

        dPunto1.setText("Punto 1:");

        eP1.setText("-");

        dPerimetro.setText("Perimetro:");

        dP2.setText("-");

        dP1.setText("-");

        ePerimetro.setText("Perimetro:");

        eP2.setText("-");

        ePunto1.setText("Punto 1:");

        eP3.setText("-");

        eTiempo.setText("Tiempo:");

        ePunto2.setText("Punto 2:");

        ePunto3.setText("Punto 3:");

        exhaustivo.setText("Exhaustivo");
        exhaustivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exhaustivoActionPerformed(evt);
            }
        });

        divideyvenceras.setText("Divide y Vencerás");
        divideyvenceras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideyvencerasActionPerformed(evt);
            }
        });

        eP5.setText("-");

        dP4.setText("-");

        dTiempo.setText("Tiempo:");

        dP3.setText("-");

        dPunto3.setText("Punto 3:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Exhaustivo & Divide y Vencerás");

        graficaCentral.setMaximumSize(new java.awt.Dimension(32767, 550));

        javax.swing.GroupLayout graficaCentralLayout = new javax.swing.GroupLayout(graficaCentral);
        graficaCentral.setLayout(graficaCentralLayout);
        graficaCentralLayout.setHorizontalGroup(
            graficaCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        graficaCentralLayout.setVerticalGroup(
            graficaCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        modoEtiquetaDyV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vi (X, Y)", "Vi", "vacío" }));
        modoEtiquetaDyV.setSelectedIndex(2);
        modoEtiquetaDyV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoEtiquetaDyVActionPerformed(evt);
            }
        });

        jLabel16.setText("Cambiar modo de las Etiquetas");

        ayudaCheck.setSelected(true);
        ayudaCheck.setText("Ayuda para localizar la solución");
        ayudaCheck.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        ayudaCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaCheckActionPerformed(evt);
            }
        });

        dividirXCheck.setSelected(true);
        dividirXCheck.setText("Mejora dividir por EjeX/Y");
        dividirXCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirXCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graficaCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modoEtiquetaDyV, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ayudaCheck, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ePunto3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eP3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ePunto2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eP2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ePunto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eP1)))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(eTiempo)
                        .addGap(18, 18, 18)
                        .addComponent(eP5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ePerimetro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eP4))
                    .addComponent(exhaustivo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dPunto3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dP3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dPunto2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dP2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dPunto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dP1)))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dTiempo)
                        .addGap(18, 18, 18)
                        .addComponent(dP5))
                    .addComponent(divideyvenceras)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dPerimetro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dP4))
                    .addComponent(dividirXCheck))
                .addGap(0, 207, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dPunto1)
                                    .addComponent(dPerimetro)
                                    .addComponent(dP1)
                                    .addComponent(dP4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dPunto2)
                                    .addComponent(dTiempo)
                                    .addComponent(dP2)
                                    .addComponent(dP5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dPunto3)
                                        .addComponent(dP3))
                                    .addComponent(divideyvenceras)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ePunto1)
                                    .addComponent(ePerimetro)
                                    .addComponent(eP1)
                                    .addComponent(eP4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ePunto2)
                                    .addComponent(eTiempo)
                                    .addComponent(eP2)
                                    .addComponent(eP5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ePunto3)
                                        .addComponent(eP3)
                                        .addComponent(ayudaCheck))
                                    .addComponent(exhaustivo)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(modoEtiquetaDyV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dividirXCheck)
                .addGap(29, 29, 29)
                .addComponent(graficaCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Panel.addTab("DyV", jPanel2);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Árbol de recubrimiento mínimo");

        primBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        primBut.setText("Algoritmo Prim");
        primBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primButActionPerformed(evt);
            }
        });

        kruskalBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        kruskalBut.setText("Algoritmo Kruskal");
        kruskalBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kruskalButActionPerformed(evt);
            }
        });

        guardarGrafosBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        guardarGrafosBut.setText("Generar Fichero");
        guardarGrafosBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarGrafosButActionPerformed(evt);
            }
        });

        graficaGrafo.setMaximumSize(new java.awt.Dimension(0, 571));

        javax.swing.GroupLayout graficaGrafoLayout = new javax.swing.GroupLayout(graficaGrafo);
        graficaGrafo.setLayout(graficaGrafoLayout);
        graficaGrafoLayout.setHorizontalGroup(
            graficaGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1007, Short.MAX_VALUE)
        );
        graficaGrafoLayout.setVerticalGroup(
            graficaGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        aristasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "VOrigen", "VDestino", "Coste"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        aristasTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(aristasTable);
        if (aristasTable.getColumnModel().getColumnCount() > 0) {
            aristasTable.getColumnModel().getColumn(0).setResizable(false);
            aristasTable.getColumnModel().getColumn(1).setResizable(false);
            aristasTable.getColumnModel().getColumn(2).setResizable(false);
        }

        costeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        costeLabel.setText("Coste Total: -");

        tiempoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tiempoLabel.setText("Tiempo: -");

        verGrafoBut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        verGrafoBut.setText("Ver Grafo");
        verGrafoBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verGrafoButActionPerformed(evt);
            }
        });

        jLabel18.setText("Modo de las Etiquetas");

        modoEtiquetaGrafo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vi (X, Y)", "Vi", "vacío" }));
        modoEtiquetaGrafo.setSelectedIndex(1);
        modoEtiquetaGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoEtiquetaGrafoActionPerformed(evt);
            }
        });

        desarrolloCheck.setText("Imprimir desarrollo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desarrolloCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modoEtiquetaGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(verGrafoBut, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(primBut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kruskalBut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardarGrafosBut))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costeLabel)
                            .addComponent(tiempoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(graficaGrafo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(primBut)
                    .addComponent(kruskalBut)
                    .addComponent(guardarGrafosBut)
                    .addComponent(verGrafoBut)
                    .addComponent(modoEtiquetaGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(desarrolloCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tiempoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(costeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
                    .addComponent(graficaGrafo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Panel.addTab("Greedy", jPanel1);

        greedyBut.setBackground(new java.awt.Color(51, 51, 51));
        greedyBut.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        greedyBut.setForeground(new java.awt.Color(255, 255, 255));
        greedyBut.setText("GREEDY");
        greedyBut.setPreferredSize(new java.awt.Dimension(390, 70));
        greedyBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greedyButActionPerformed(evt);
            }
        });

        datosBut.setBackground(new java.awt.Color(51, 51, 51));
        datosBut.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        datosBut.setForeground(new java.awt.Color(255, 255, 255));
        datosBut.setText("DATOS");
        datosBut.setOpaque(false);
        datosBut.setPreferredSize(new java.awt.Dimension(400, 70));
        datosBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosButActionPerformed(evt);
            }
        });

        dyvBut.setBackground(new java.awt.Color(51, 51, 51));
        dyvBut.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        dyvBut.setForeground(new java.awt.Color(255, 255, 255));
        dyvBut.setText("DIVIDE Y VENCERÁS");
        dyvBut.setPreferredSize(new java.awt.Dimension(400, 70));
        dyvBut.setRequestFocusEnabled(false);
        dyvBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dyvButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(datosBut, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dyvBut, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(greedyBut, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dyvBut, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datosBut, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greedyBut, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void divideyvencerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideyvencerasActionPerformed
        try{
            ArrayList<Vertice> t = new ArrayList<Vertice>();
            t = vertices;
            boolean dividirX=true; //Por defecto se divide por el ejeX
            long start = System.currentTimeMillis();
            if(mejoraDyV) //Si está activada la mejora
                if(Desviacion.desviacionEstandar(vertices)<25) //Si los puntos se concentran mucho entorno a la media X
                    dividirX=false; //Dividiremos por el eje Y
            HeapSort.ordenar(t,dividirX); //Tambien ordenaremos por el eje x/y
            Trio sol = AlgoritmosDyV.DyVNuevo(t, 0, t.size() - 1,dividirX);
            double elapsedTime = (System.currentTimeMillis() - start) / 1000.0;

            String pattern = "###.##", x, y;
            DecimalFormat decimalFormat = new DecimalFormat(pattern);
            decimalFormat.setRoundingMode(RoundingMode.DOWN);

            x = decimalFormat.format(sol.getP1().getX());
            y = decimalFormat.format(sol.getP1().getY());
            dP1.setText("("+x + " , " + y+")");

            x = decimalFormat.format(sol.getP2().getX());
            y = decimalFormat.format(sol.getP2().getY());
            dP2.setText("("+x + " , " + y+")");

            x = decimalFormat.format(sol.getP3().getX());
            y = decimalFormat.format(sol.getP3().getY());
            dP3.setText("("+x + " , " + y+")");

            x = decimalFormat.format(sol.getDistancia());
            dP4.setText(x);
            dP5.setText(Double.toString(elapsedTime)+" s");
            graficaCentral.representaSol(sol);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Debe generar el conjunto de datos primero!","Error",  JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_divideyvencerasActionPerformed

    private void exhaustivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exhaustivoActionPerformed
        try
        {
            long start = System.currentTimeMillis();
            Trio sol = AlgoritmosDyV.exhaustivo(vertices, 0, vertices.size() - 1);
            double elapsedTime = (System.currentTimeMillis() - start) / 1000.0;

            String pattern = "###.##", x, y;
            DecimalFormat decimalFormat = new DecimalFormat(pattern);
            decimalFormat.setRoundingMode(RoundingMode.DOWN);

            x = decimalFormat.format(sol.getP1().getX());
            y = decimalFormat.format(sol.getP1().getY());
            eP1.setText("("+x + " , " + y+")");

            x = decimalFormat.format(sol.getP2().getX());
            y = decimalFormat.format(sol.getP2().getY());
            eP2.setText("("+x + " , " + y+")");

            x = decimalFormat.format(sol.getP3().getX());
            y = decimalFormat.format(sol.getP3().getY());
            eP3.setText("("+x + " , " + y+")");

            x = decimalFormat.format(sol.getDistancia());
            eP4.setText(x);
            eP5.setText(Double.toString(elapsedTime)+" s");
            graficaCentral.representaSol(sol);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Debe generar el conjunto de datos primero!","Error",  JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_exhaustivoActionPerformed

    private void primButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primButActionPerformed
    try{
        long start = System.currentTimeMillis();
        aristas = AlgoritmosV.Prim(g);
        double elapsedTime = (System.currentTimeMillis() - start)/1000.0;
        double costeTotal=0;
       
        for(Arista a : aristas){
            costeTotal += a.getCoste();
            
        }
        
        anadirFilaAristas(aristas);
        graficaGrafo.addPuntos(vertices);
        graficaGrafo.addAristas(aristas);
        graficaGrafo.representa();
        
        String pattern = "####.##";
        DecimalFormat decimalFormat = new DecimalFormat(pattern);
        decimalFormat.setMaximumFractionDigits(2);
        decimalFormat.setRoundingMode(RoundingMode.UP);
        
        costeLabel.setText("Coste total: "+decimalFormat.format(costeTotal));
        tiempoLabel.setText("Tiempo: "+elapsedTime+" s");
    }catch(java.util.NoSuchElementException ex)
    {
        JOptionPane.showMessageDialog(this, "Debe generar el conjunto de datos primero!","Error",  JOptionPane.ERROR_MESSAGE);
    }

        
    }//GEN-LAST:event_primButActionPerformed

    private void guardarGrafosButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarGrafosButActionPerformed
        try
        {
            double costeTotal=-1;
            for(Arista a : aristas)
            costeTotal += a.getCoste();
            JFileChooser fileChooser = new JFileChooser();
            
            FileFilter tsp = new FileFilter() {
            public String getDescription() {
                return "Fichero TSP (*.tsp)";
            }

            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else {
                    return f.getName().toLowerCase().endsWith(".tsp");
                }
            }
            };
            
            fileChooser.addChoosableFileFilter(tsp);
            fileChooser.setFileFilter(tsp);
            
            fileChooser.setDialogTitle("Guardar solución en un fichero");
            int userSelection = fileChooser.showSaveDialog(this);

            if (userSelection == JFileChooser.APPROVE_OPTION) {
                File fileToSave = fileChooser.getSelectedFile();
                
                String msg = "Fichero guardado en "+fileToSave.getAbsolutePath();
                if(fileChooser.getFileFilter().equals(tsp)){ //Si cumple el formato .tsp
                  Fichero.guardarCamino(aristas, costeTotal, Paths.get(fileToSave.getAbsolutePath()+".tsp"));
                  msg+=".tsp";
                }
                else 
                     Fichero.guardarCamino(aristas, costeTotal, Paths.get(fileToSave.getAbsolutePath()));
                
                
                JOptionPane.showMessageDialog(this,msg,msg,JOptionPane.WARNING_MESSAGE);
            }
        }catch(java.lang.NullPointerException Ex)
        {
            JOptionPane.showMessageDialog(this, "Debe generar el grafo primero!", "Error al guardar fichero!",  JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error al guardar fichero!",  JOptionPane.ERROR_MESSAGE);
            
        }
        

    }//GEN-LAST:event_guardarGrafosButActionPerformed
    private void generarGrafo()
    {
        this.g = new Grafo();
        
        vertices.forEach((v) -> {    //Añadimos cada vertice al grafo
            g.anadirVertice(v);
        });
        
        for(int i=0; i<this.vertices.size(); i++)
            for(int j=i+1; j<this.vertices.size(); j++)
            {
                Arista a = new Arista(vertices.get(i), vertices.get(j));
                g.anadirArista(a);       
            }
    }
    private void verGrafoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verGrafoButActionPerformed

        if(vertices.size()>40) //Si tenemos muchos vertices, mostramos el mensajito de espera
        {
            
            graficaGrafo.limpiar();
            verGrafo(); //Lo ejecutamos en un hilo aparte para poder mostrar el siguiente cuadro de dialogo
            
            try {
            musica = AudioSystem.getClip();
            AudioInputStream inputStream = AudioSystem.getAudioInputStream(
            Menu.class.getResourceAsStream("/espera/cancionEspera.wav"));
            musica.open(inputStream);
            musica.start(); 
            }catch(Exception ex)
            {
                System.out.println(ex.getMessage());   
            }
            
            //MOSTRAR DIALOGO
            ImageIcon imagen = new ImageIcon(getClass().getResource("/espera/mono.gif"));
            String texto = "Por favor espere...\nSe está generando el grafo de forma que\n"
                   + "partan n-1 aristas de cada vértice y\nconecten con el resto de vértices\n\nEste proceso puede ser lento en grafos de +40 vértices\n"
                    + "\nPuede ver la solución directamente clicando\nen el botón del algoritmo de Prim o Kruskal";

 
            JPanel panelImagen = new JPanel(new BorderLayout());
            panelImagen.add(new JLabel(imagen));

            
            paneCargando = new JOptionPane(panelImagen);
            int ok = JOptionPane.showOptionDialog(this,texto, "Generando grafo...",JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE, imagen, new Object[]{"Cerrar"} ,null);
            if(ok==JOptionPane.OK_OPTION)
            {
                musica.stop();
            }

        }
        else //Si tenemos pocos vertices, lo hacemos del tiron
        {
            graficaGrafo.addPuntos(vertices);
            graficaGrafo.addAristas(g.cjtoAristas);
            graficaGrafo.representa();
        }
              
    }//GEN-LAST:event_verGrafoButActionPerformed

    private void greedyButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greedyButActionPerformed
        Panel.setSelectedIndex(2);
        graficaGrafo.setModoEtiqueta(1);
        generarGrafo();
        graficaGrafo.removeAll(); //Limpia 
        graficaGrafo.addPuntos(new ArrayList<>());
        graficaGrafo.representa(); // y muestra la grafica vacia
        
    }//GEN-LAST:event_greedyButActionPerformed

    private void datosButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosButActionPerformed
        Panel.setSelectedIndex(0);
    }//GEN-LAST:event_datosButActionPerformed

    private void dyvButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dyvButActionPerformed
        Panel.setSelectedIndex(1);
        this.graficaCentral.addPuntos(vertices);
        System.out.println("DESVIACION ESTANDAR: "+Desviacion.desviacionEstandar(vertices));
        graficaCentral.representa();
    }//GEN-LAST:event_dyvButActionPerformed

    private void aleatoriosButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aleatoriosButActionPerformed
        vertices.clear();
        try {
            double max = Double.parseDouble(rangoDchPane.getText());
            double min = Double.parseDouble(rangoIzqPane.getText());

            if (aleatoriosPane.getText().matches("[0-9]+")) {
                for (int i = 0; i < Integer.parseInt(aleatoriosPane.getText()); i++) {
                    double x = (Math.random() * (max - min) + min);
                    double y = (Math.random() * (max - min) + min);
                    vertices.add(new Vertice(i + 1, x, y));
                }
                this.actualizarDatos();

            } else {
                JOptionPane.showMessageDialog(this, "Número inválido!", "Número Inválido!", JOptionPane.ERROR_MESSAGE);
            }

        } catch (java.lang.NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Rango inválido!", "Rango Inválido!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aleatoriosButActionPerformed

    private void mostrarPuntosButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarPuntosButActionPerformed

        Panel.setSelectedIndex(1);
    }//GEN-LAST:event_mostrarPuntosButActionPerformed

    private void guardarButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButActionPerformed

        
    }//GEN-LAST:event_guardarButActionPerformed

    private void examinarButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examinarButActionPerformed
       
    }//GEN-LAST:event_examinarButActionPerformed

    private void cargarButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarButActionPerformed

        this.vertices.clear();
        this.actualizarDatos();
    }//GEN-LAST:event_cargarButActionPerformed

    private void eliminarButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButActionPerformed
        if (!eliminarPane.getText().isEmpty() && eliminarPane.getText().matches("[0-9]+")) {
            try {
                for (Vertice p : vertices)//Recorremos el array de puntos
                {
                    if (p.getID() == Integer.parseInt(eliminarPane.getText())) {
                        vertices.remove(p);
                        break;
                    }
                }
                this.actualizarDatos();
            } catch (java.lang.IndexOutOfBoundsException ex) {
                JOptionPane.showMessageDialog(this, "Punto inválido!", "Punto Inválido!", JOptionPane.ERROR_MESSAGE);
            }

        } else //Cuadro de texto vacio
        {
            JOptionPane.showMessageDialog(this, "ID inválido!", "ID Inválido!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eliminarButActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        if (puntoX.getText().isEmpty() || puntoY.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, rellene todos los valores.");
        } else {
            //if (puntoX.getText().matches("[0-9]+.") && puntoY.getText().matches("[0-9]+.")) {
                double x = Double.parseDouble(puntoX.getText().trim());
                double y = Double.parseDouble(puntoY.getText().trim());
                Vertice punto;
                if (vertices.isEmpty()) {
                    punto = new Vertice(1, x, y);
                } else {
                    punto = new Vertice(vertices.get(vertices.size() - 1).getID() + 1, x, y);
                }
                vertices.add(punto);

                this.actualizarDatos();
                //} else {
                //   JOptionPane.showMessageDialog(null, "Por favor, introduzca numeros.");
                //}

            //this.savePointstoFile();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void guardarFichButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarFichButActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileFilter tsp = new FileFilter() {
            public String getDescription() {
                return "Fichero TSP (*.tsp)";
            }

            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else {
                    return f.getName().toLowerCase().endsWith(".tsp");
                }
            }
            };
            
            fileChooser.addChoosableFileFilter(tsp);
            fileChooser.setFileFilter(tsp);
        
        fileChooser.setDialogTitle("Guardar puntos en un fichero");
        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            String msg = "Fichero guardado en " + fileToSave.getAbsolutePath();
            Fichero f;
            if(fileChooser.getFileFilter().equals(tsp)){
                f = new Fichero(fileToSave.getAbsolutePath()+".tsp");
                msg+=".tsp";
            }
            else{
                f = new Fichero(fileToSave.getAbsolutePath());
            }
            JOptionPane.showMessageDialog(this, msg, msg, JOptionPane.WARNING_MESSAGE);
            
            f.guardarPuntos(vertices);
        }
    }//GEN-LAST:event_guardarFichButActionPerformed

    private void cargarFichButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarFichButActionPerformed
         // muestra el cuadro de diálogo de archivos, para que el usuario pueda elegir el archivo a abrir
        JFileChooser selectorArchivos = new JFileChooser();
        selectorArchivos.setFileSelectionMode(JFileChooser.FILES_ONLY);

        // indica cual fue la accion de usuario sobre el jfilechooser
        int resultado = selectorArchivos.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            //try {
                File archivo = selectorArchivos.getSelectedFile(); // obtiene el archivo seleccionado

                // muestra error si es inválido
                if ((archivo == null) || (archivo.getName().equals(""))) {
                    JOptionPane.showMessageDialog(this, "Error al cargar fichero", "Nombre de archivo inválido", JOptionPane.ERROR_MESSAGE);
                } // fin de if

                //cargarBut.doClick();
                try {
                    Fichero lf = new Fichero(archivo.getAbsolutePath());
                    this.vertices.clear();
                    this.vertices = lf.procesar();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error al cargar fichero", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
                }
                this.actualizarDatos();
            }
    }//GEN-LAST:event_cargarFichButActionPerformed

    private void kruskalButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kruskalButActionPerformed
        try{            
            long start = System.currentTimeMillis();
            aristas = AlgoritmosV.Kruskal(g,desarrolloCheck.isSelected());
            double elapsedTime = (System.currentTimeMillis() - start)/1000.0;
            double costeTotal=0;
            
            ArrayList<Vertice> vertices = new ArrayList<>();
            for(Arista a : aristas){
                costeTotal += a.getCoste();
                vertices.add(a.getOrigen());
                if(vertices.indexOf(a.getDestino())==-1) vertices.add(a.getDestino());
            }

            anadirFilaAristas(aristas);
            graficaGrafo.addPuntos(vertices);
            graficaGrafo.addAristas(aristas);
            graficaGrafo.representa();

            String pattern = "####.##";
            DecimalFormat decimalFormat = new DecimalFormat(pattern);
            decimalFormat.setMaximumFractionDigits(2);
            decimalFormat.setRoundingMode(RoundingMode.UP);

            costeLabel.setText("Coste total: "+decimalFormat.format(costeTotal));
            tiempoLabel.setText("Tiempo: "+elapsedTime+" s");
    }catch(java.util.NoSuchElementException ex)
    {
        JOptionPane.showMessageDialog(this, "Debe generar el conjunto de datos primero!","Error",  JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_kruskalButActionPerformed

    private void modoEtiquetaDyVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoEtiquetaDyVActionPerformed
        graficaCentral.setModoEtiqueta(modoEtiquetaDyV.getSelectedIndex());
    }//GEN-LAST:event_modoEtiquetaDyVActionPerformed

    private void modoEtiquetaDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoEtiquetaDatosActionPerformed
        graficaDatos.setModoEtiqueta(modoEtiquetaDatos.getSelectedIndex());
    }//GEN-LAST:event_modoEtiquetaDatosActionPerformed

    private void modoEtiquetaGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoEtiquetaGrafoActionPerformed
       graficaGrafo.setModoEtiqueta(modoEtiquetaGrafo.getSelectedIndex());
    }//GEN-LAST:event_modoEtiquetaGrafoActionPerformed

    private void ayudaCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaCheckActionPerformed
        if(ayudaCheck.isSelected())
             graficaCentral.setAyuda(true);
        else
             graficaCentral.setAyuda(false);
        //divideyvenceras.doClick();
        
    }//GEN-LAST:event_ayudaCheckActionPerformed

    private void ficheroComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficheroComboActionPerformed
       String opcion = ficheroCombo.getSelectedItem().toString();
       if(!opcion.equals("SELECCIONAR"))
       {
           try{
               Fichero fich = new Fichero("res/dataset/"+opcion+".tsp");
               vertices.clear();
               vertices = fich.procesar();
               actualizarDatos();
           }catch(Exception ex)
           {
               System.out.println(ex.getMessage());
               JOptionPane.showMessageDialog(this, "Error al cargar fichero", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
           } 
       }
    }//GEN-LAST:event_ficheroComboActionPerformed

    private void dividirXCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividirXCheckActionPerformed
        if(dividirXCheck.isSelected())
            mejoraDyV=true;
        else
            mejoraDyV=false;
        
    }//GEN-LAST:event_dividirXCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                Menu menu = new Menu();
                menu.setVisible(true);
                  }
            });
        

                    

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Datos;
    private javax.swing.JTabbedPane Panel;
    private javax.swing.JButton aleatoriosBut;
    private javax.swing.JTextPane aleatoriosPane;
    private javax.swing.JTable aristasTable;
    private javax.swing.JCheckBox ayudaCheck;
    private javax.swing.JButton cargarBut;
    private javax.swing.JButton cargarFichBut;
    private javax.swing.JLabel costeLabel;
    private javax.swing.JLabel dP1;
    private javax.swing.JLabel dP2;
    private javax.swing.JLabel dP3;
    private javax.swing.JLabel dP4;
    private javax.swing.JLabel dP5;
    private javax.swing.JLabel dPerimetro;
    private javax.swing.JLabel dPunto1;
    private javax.swing.JLabel dPunto2;
    private javax.swing.JLabel dPunto3;
    private javax.swing.JLabel dTiempo;
    private javax.swing.JButton datosBut;
    private javax.swing.JCheckBox desarrolloCheck;
    private javax.swing.JButton divideyvenceras;
    private javax.swing.JCheckBox dividirXCheck;
    private javax.swing.JButton dyvBut;
    private javax.swing.JLabel eP1;
    private javax.swing.JLabel eP2;
    private javax.swing.JLabel eP3;
    private javax.swing.JLabel eP4;
    private javax.swing.JLabel eP5;
    private javax.swing.JLabel ePerimetro;
    private javax.swing.JLabel ePunto1;
    private javax.swing.JLabel ePunto2;
    private javax.swing.JLabel ePunto3;
    private javax.swing.JLabel eTiempo;
    private javax.swing.JButton eliminarBut;
    private javax.swing.JTextPane eliminarPane;
    private javax.swing.JButton examinarBut;
    private javax.swing.JButton exhaustivo;
    private javax.swing.JComboBox<String> ficheroCombo;
    private AMC1.Comun.Grafica graficaCentral;
    private AMC1.Comun.Grafica graficaDatos;
    private AMC1.Comun.Grafica graficaGrafo;
    private javax.swing.JButton greedyBut;
    private javax.swing.JButton guardarBut;
    private javax.swing.JButton guardarFichBut;
    private javax.swing.JButton guardarGrafosBut;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kruskalBut;
    private javax.swing.JComboBox<String> modoEtiquetaDatos;
    private javax.swing.JComboBox<String> modoEtiquetaDyV;
    private javax.swing.JComboBox<String> modoEtiquetaGrafo;
    private javax.swing.JButton mostrarPuntosBut;
    private javax.swing.JButton primBut;
    private javax.swing.JTextPane puntoX;
    private javax.swing.JTextPane puntoY;
    private javax.swing.JTextPane rangoDchPane;
    private javax.swing.JTextPane rangoIzqPane;
    private javax.swing.JLabel tiempoLabel;
    private javax.swing.JButton verGrafoBut;
    // End of variables declaration//GEN-END:variables
}
